### ISSUE TITLE
fiscal vs. calendar year

### ISSUE THREAD

**Issue by emr65df** [acep-uaf/ak-energy-statistics-2011_2021#12]
We (Emily R. & Alana) were reviewing the [code](https://github.com/acep-uaf/ak-energy-statistics-2011_2021/blob/csv/trends/price_inflation_pce.Rmd) that pulls AK CPI data in order to adjust prices per kwh for inflation based on the most recent year's worth of data as found in this [file](https://github.com/acep-uaf/ak-energy-statistics-2011_2021/blob/csv/trends/raw/price_inflation_pce.csv), and we were trying to determine if this was based on calendar or fiscal year data. It looks like FRED reports both (calendar and annual year) and that the script is averaging the two. I recommend choose one or the other and clearly state which year definition you are using. Or use both in separate columns if that makes sense. Often, fiscal year data is what is reported by the industry and used. Please let us know your thoughts.

**Comment by jikaczmarski** [comment]
I've reviewed the code and I agree, it's interesting to see the CPI reported for both calendar and fiscal year. One of our main issues at the moment is not being able to understand if the PCE data that has been provided to us at an annual time step is actually fiscal or calendar year averages. We'll know more soon and that would clear up our use of the CPI. However, the most straight forward approach would be to use the calendar year CPI for data sourced from EIA since they report calendar year, and the fiscal year CPI for the PCE communities *if* we can confirm that it is indeed FY averages.

**Comment by jikaczmarski** [comment]
@ianalexmac The PCE workbooks actually state that the PCE data is calendar year. We'll want to redo the CPI adjustment to only use the calendar year series.

**Comment by ianalexmac** [comment]
@jikaczmarski CPI data was truncated to January-only data, thereby making it Calendar Year.

@emr65df  I've tried to maintain a light touch on the schema in order to facilitate future table joins etc, even going so far as to preserve archaic column names (ex: `AEA Sales Reporting ID`). You bring up a great point, but I'm very leery of changing column names at this point, especially as so much code is riding on these names. Certainly in future iterations of this project we will have the opportunity to frame-out the schemas as we see fit, but that may have to be at a later date. For now, both the workbooks and CPI data are Calendar Year, which will be written up in the documentation. But I think we should kick this can down the road and leave the column name as `Year`.
